/**
 * about — Server identity, version, data sources, and tool catalog.
 *
 * Generated by scripts/apply-sector-regulator-golden-standard.py from sources.yml + package.json.
 * To update, edit sources.yml or package.json and re-run the helper.
 */

import { TOOL_NAMES } from "./registry.js";

export type AboutInput = Record<string, never>;

const SERVER_NAME = "finnish-financial-regulation-mcp";
const VERSION = "0.1.0";
const DESCRIPTION = "Finanssivalvonta (FIN-FSA) MCP server — määräykset, ohjeet, kannanotot ja valvontatoimet";
const JURISDICTION = "FI";
const CATEGORY = "financial-regulation";

const SOURCES_SUMMARY: Array<{ name: string; url: string; license: string }> = [
    {
      name: "FIN-FSA Regulations (Maaraykset)",
      url: "https://www.finanssivalvonta.fi/en/regulation/FIN-FSA-regulations/",
      license: "Public regulatory publication",
    },
    {
      name: "FIN-FSA Guidelines (Ohjeet)",
      url: "https://www.finanssivalvonta.fi/en/regulation/FIN-FSA-regulations/",
      license: "Public regulatory publication",
    },
    {
      name: "FIN-FSA Regulatory Statements (Kannanotot)",
      url: "https://www.finanssivalvonta.fi/en/regulation/FIN-FSA-regulations/",
      license: "Public regulatory publication",
    },
    {
      name: "FIN-FSA Supervisory Measures",
      url: "https://www.finanssivalvonta.fi/en/about-the-fin-fsa/powers-and-funding/powers-and-authority/supervisory-measures/",
      license: "Public regulatory publication",
    },
  ];

export async function about(
  _input: AboutInput,
): Promise<{
  name: string;
  version: string;
  description: string;
  jurisdiction: string;
  category: string;
  sources: Array<{ name: string; url: string; license: string }>;
  tools: string[];
  disclaimer: string;
  _metadata: { tool: string };
}> {
  return {
    name: SERVER_NAME,
    version: VERSION,
    description: DESCRIPTION,
    jurisdiction: JURISDICTION,
    category: CATEGORY,
    sources: SOURCES_SUMMARY,
    tools: [...TOOL_NAMES],
    disclaimer:
      "This is a research tool, not legal or compliance advice. Verify critical citations against authoritative sources.",
    _metadata: { tool: "about" },
  };
}
