/**
 * list_sources — Expose data provenance metadata as an MCP tool.
 *
 * Returns information about the authoritative data sources backing this server,
 * including coverage, freshness, and licensing.
 *
 * Generated by scripts/apply-sector-regulator-golden-standard.py from sources.yml.
 * To update, edit sources.yml and re-run the helper.
 */

export type ListSourcesInput = Record<string, never>;

interface SourceInfo {
  name: string;
  authority: string;
  url: string;
  license: string;
  coverage: string;
  languages: string[];
  last_verified: string | null;
}

const MCP_NAME = "finnish-financial-regulation-mcp";
const JURISDICTION = "FI";

const SOURCES: SourceInfo[] = [
    {
      name: "FIN-FSA Regulations (Maaraykset)",
      authority: "",
      url: "https://www.finanssivalvonta.fi/en/regulation/FIN-FSA-regulations/",
      license: "Public regulatory publication",
      coverage: "",
      languages: [],
      last_verified: "2026-05-10",
    },
    {
      name: "FIN-FSA Guidelines (Ohjeet)",
      authority: "",
      url: "https://www.finanssivalvonta.fi/en/regulation/FIN-FSA-regulations/",
      license: "Public regulatory publication",
      coverage: "",
      languages: [],
      last_verified: "2026-05-10",
    },
    {
      name: "FIN-FSA Regulatory Statements (Kannanotot)",
      authority: "",
      url: "https://www.finanssivalvonta.fi/en/regulation/FIN-FSA-regulations/",
      license: "Public regulatory publication",
      coverage: "",
      languages: [],
      last_verified: "2026-05-10",
    },
    {
      name: "FIN-FSA Supervisory Measures",
      authority: "",
      url: "https://www.finanssivalvonta.fi/en/about-the-fin-fsa/powers-and-funding/powers-and-authority/supervisory-measures/",
      license: "Public regulatory publication",
      coverage: "",
      languages: [],
      last_verified: "2026-05-10",
    },
  ];

export async function listSources(
  _input: ListSourcesInput,
): Promise<{
  mcp_name: string;
  jurisdiction: string;
  sources: SourceInfo[];
  _metadata: { tool: string; source_authority: string };
}> {
  return {
    mcp_name: MCP_NAME,
    jurisdiction: JURISDICTION,
    sources: SOURCES,
    _metadata: {
      tool: "list_sources",
      source_authority: SOURCES.map((s) => s.authority).join(", "),
    },
  };
}
